# Generated by Django 5.0.4 on 2024-04-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
    ]
