# Generated by Django 5.0.4 on 2024-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
