# Generated by Django 5.0.4 on 2024-04-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_user_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdetails',
        ),
    ]
