# Generated by Django 5.0.4 on 2024-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_userdetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=10, null=True),
        ),
    ]
