# Generated by Django 5.0.4 on 2024-04-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_userdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(default='default-<django.db.models.fields.CharField>.jpg', upload_to='profile_pics'),
        ),
    ]
