# Generated by Django 5.0.4 on 2024-04-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_userdetails_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('text', models.TextField()),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('liked_by', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('email', models.EmailField(max_length=100)),
                ('handle', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.userdetails')),
            ],
        ),
    ]
