# Generated by Django 5.0.4 on 2024-04-15 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_text',
            fields=[
                ('text', models.TextField()),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.userdetails')),
            ],
        ),
    ]
