# Generated by Django 5.0.4 on 2024-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='friend_requests',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='friend_requests_sent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='friends',
            field=models.TextField(default=''),
        ),
    ]
