# Generated by Django 5.0.4 on 2024-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_userdetails_bio_userdetails_friend_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='handle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
