# Generated by Django 5.0.4 on 2024-04-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_userdetails_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='contact_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='hobbies',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
